CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y

CONFIG_PINCTRL=y
CONFIG_CLOCK_CONTROL=y
CONFIG_DMA=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ASSERT=y
CONFIG_MCX_MAC_EDMA_LINKED=n
CONFIG_MCX_MAC_SOLID_VIDEO_DIAG=n
CONFIG_MCX_MAC_HARDWARE_VIDEO_DIAG=n
CONFIG_MCX_MAC_CONTINUOUS_RASTER=y
CONFIG_MCX_MAC_ANIMATED_TEST=n
CONFIG_MCX_MAC_M68K_BUS_DIAG=y
CONFIG_MCX_MAC_UMAC_CORE=y
CONFIG_MCX_MAC_UMAC_SMOKE=y
CONFIG_DMA_TCD_QUEUE_SIZE=2
