CONFIG_USB_HOST_STACK=y
CONFIG_MCX_MAC_USB_MOUSE=y
CONFIG_USBH_USB_DEVICE_MAX=2
CONFIG_USBH_USB_DEVICE_HEAP=1024
CONFIG_USBH_STACK_SIZE=2048
CONFIG_UHC_NXP_THREAD_STACK_SIZE=2048
CONFIG_ISR_STACK_SIZE=2048
CONFIG_STACK_SENTINEL=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
